name: "Debian: Build Package"

on:
  - push

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: "Build"
    steps:
      - uses: pkgstore/github-action-build-deb@main
        with:
          repo_src: "https://github.com/${{ github.repository }}.git"
          repo_dst: "https://github.com/deb-store/ext-zsh.git"
          user_name: "${{ secrets.BOT_NAME }}"
          user_email: "${{ secrets.BOT_EMAIL }}"
          user_token: "${{ secrets.BOT_TOKEN }}"
